version: '2'
services:
    fy17_q2-app:
        image: fy17_q2
        external_links:
            - fy17_q2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fy17_q2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fy17_q2-mysql:
        extends:
            file: mysql.yml
            service: fy17_q2-mysql
