version: '2'
services:
    fy17_q2-mysql:
        container_name: fy17_q2-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/FY17_Q2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=fy17_q2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
